{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-barcoder
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/baRcodeR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/baRcodeR/baRcodeR_{{ version }}.tar.gz
  sha256: dc58b650039f243eb5da8b20b2cd3a4d665197183a1094826ee65f78f96a2ca5

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dt >=0.3
    - r-miniui >=0.1.1
    - r-qrcode
    - r-rstudioapi
    - r-shiny >=0.13
  run:
    - r-base
    - r-dt >=0.3
    - r-miniui >=0.1.1
    - r-qrcode
    - r-rstudioapi
    - r-shiny >=0.13

test:
  commands:
    - $R -e "library('baRcodeR')"           # [not win]
    - "\"%R%\" -e \"library('baRcodeR')\""  # [win]

about:
  home: https://github.com/yihanwu/baRcodeR
  license: GPL-3.0-only
  summary: 'Tools to generate unique identifiers and printable barcoded labels for sample management.  The creation of unique ID codes and printable PDF files can be initiated by standard commands,  user prompts, or through a GUI addin for R Studio. Both single-level and hierarchical labels can  be created in the command
    line interactively or non-interactively. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: baRcodeR
# Title: Labelling, Tracking, and Collecting Data from Biological Samples
# Version: 0.1.3
# Authors@R: c(person("Yihan", "Wu", role="aut", email = "yihan.wu@queensu.ca"), person("Robert", "Colautti", email = "robert.colautti@queensu.ca", role = c("aut", "cre")))
# Maintainer: Robert Colautti <robert.colautti@queensu.ca>
# Description: Tools to generate unique identifiers and printable barcoded labels for sample management.  The creation of unique ID codes and printable PDF files can be initiated by standard commands,  user prompts, or through a GUI addin for R Studio. Both single-level and hierarchical labels can  be created in the command line interactively or non-interactively.
# Depends: R (>= 3.4.0), qrcode
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Imports: DT (>= 0.3), grDevices, grid, miniUI (>= 0.1.1), shiny (>= 0.13), rstudioapi
# Suggests: testthat, knitr, rmarkdown
# RoxygenNote: 6.1.0
# VignetteBuilder: knitr
# URL: https://github.com/yihanwu/baRcodeR
# BugReports: https://github.com/yihanwu/baRcodeR/issues
# NeedsCompilation: no
# Packaged: 2019-04-26 19:30:38 UTC; colauttilab
# Author: Yihan Wu [aut], Robert Colautti [aut, cre]
# Repository: CRAN
# Date/Publication: 2019-04-26 19:50:03 UTC
